'use server';
/**
 * @fileOverview A Genkit flow for generating AI responses that may include structured artifacts like code or interactive UI.
 *
 * - generateArtifacts - A function that handles the generation of AI responses and optional artifacts.
 * - GenerateArtifactsInput - The input type for the generateArtifacts function.
 * - GenerateArtifactsOutput - The return type for the generateArtifacts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateArtifactsInputSchema = z.object({
  userPrompt: z.string().describe('The user\'s prompt to the AI.'),
});
export type GenerateArtifactsInput = z.infer<typeof GenerateArtifactsInputSchema>;

const ArtifactContentSchema = z.object({
  type: z.enum(['code', 'interactive-ui', 'text']).describe('The type of artifact generated (e.g., "code" for programming snippets, "interactive-ui" for HTML/JS, "text" for rich text).'),
  content: z.string().describe('The raw content of the generated artifact.'),
  artifactName: z.string().optional().describe('An optional name or title for the artifact.'),
});

const GenerateArtifactsOutputSchema = z.object({
  aiResponse: z.string().describe('The AI\'s conversational response.'),
  artifact: ArtifactContentSchema.optional().describe('An optional structured artifact generated by the AI based on the prompt.'),
});
export type GenerateArtifactsOutput = z.infer<typeof GenerateArtifactsOutputSchema>;

export async function generateArtifacts(input: GenerateArtifactsInput): Promise<GenerateArtifactsOutput> {
  return generateArtifactsFlow(input);
}

const generateArtifactsPrompt = ai.definePrompt({
  name: 'generateArtifactsPrompt',
  input: {schema: GenerateArtifactsInputSchema},
  output: {schema: GenerateArtifactsOutputSchema},
  prompt: `You are a helpful AI assistant. Your goal is to respond to the user's prompt conversationally and, when appropriate, generate a structured 'artifact'.

If the user asks for code, a UI component, or any other structured output (e.g., "create a dashboard", "React code for a button", "write a Python script"), you should generate an 'artifact' object within your JSON response.
- For UI components or web layouts, set 'type' to 'interactive-ui' and 'content' to the HTML/CSS/JS. For example, if asked for a "dashboard", generate simple HTML for a dashboard.
- For programming code snippets, set 'type' to 'code' and 'content' to the code. For example, if asked for "React code for a button", provide React JSX.
- For any other rich structured text that isn't code or interactive UI, set 'type' to 'text'.

If no specific structured output is requested or relevant, only provide a conversational 'aiResponse'.

User prompt: {{{userPrompt}}}`,
});

const generateArtifactsFlow = ai.defineFlow(
  {
    name: 'generateArtifactsFlow',
    inputSchema: GenerateArtifactsInputSchema,
    outputSchema: GenerateArtifactsOutputSchema,
  },
  async (input) => {
    const {output} = await generateArtifactsPrompt(input);
    return output!;
  }
);
